<?php
/**
 * @file
 * A block module that displays the Onsweb Clubplugin competition data.
 * @copyright 2013 Tom Hendrikx
 * @license BSD-3 See LICENSE for details
 */


// Common settings that probably shouldn't be hidden in the code

// Informational website
define('CLUBPLUGIN_VENDOR_URI', 'http://www.onswebbond.nl/voor-verenigingen/');

// Download location of the files you need to host yourself (in libraries)
define('CLUBPLUGIN_DOWNLOAD_URI', 'http://www.onswebbond.nl/userfiles/plugin.zip');

// Path to the jquery plugin, hosted by onsweb or its partners,
//   %s gets replaced with the scriptcode
define('CLUBPLUGIN_PLUGIN_URI', 'http://www.knkv.nl/kcp/%s/');


/**
 * Implements hook_help().
 *
 * Returns basic help about how to use this plugin.
 */
function clubplugin_help($path, $arg) {
	switch ($path) {
		case 'admin/help#clubplugin':
			return '<p>'. t('Display competition data available through the Onsweb Clubplugin.') .'</p>';
			break;
	}
}


/**
 * Implements hook_block_info().
 *
 * This defines a block in the block administration area, so we can
 * actually configure where to display the data.
 */
function clubplugin_block_info() {
	$blocks['clubplugin'] = array(
		'info' => t('Clubplugin'),
		'cache' => DRUPAL_CACHE_GLOBAL,
	);
	return $blocks;
}


/**
 * Implements hook_block_view().
 *
 * This returns the actual data in the block.
 */
function clubplugin_block_view($delta = '') {
	switch ($delta) {
		case 'clubplugin':
			$block['subject'] = t('Clubplugin');
			if (user_access('access content')) {
				$block['content'] = _clubplugin_block_content();
			}
			return $block;
	}
}


/**
 * Generate block content for clubplugin.
 */
function _clubplugin_block_content() {
	// Check if we have a scriptcode, otherwise there is no data to show.
	$scriptcode = variable_get('clubplugin_scriptcode', '');
	if (empty($scriptcode)) {
		return t('Clubplugin error: no valid script code configured in the administration interface');
	}

	// Check if the library (.css) files are available
	$library = libraries_load('clubplugin');
	if (empty($library['loaded'])) {
		return t('Clubplugin error: library files could not be loaded') .' (' . $library['error'] .')';
	}

	// Add offsite js library
	$clubplugin_location = sprintf(CLUBPLUGIN_PLUGIN_URI, $scriptcode);
	drupal_add_js(sprintf($clubplugin_location, $scriptcode), 'external');

	// Add plugin init script
	drupal_add_js("jQuery(document).ready(function($){ clubplugin.load('#club-plugin'); });", array(
		'type' => 'inline',
		'group' => JS_DEFAULT,
	));

	// Return placeholder div as content
	$content = '<div id="club-plugin"><noscript>';
	$content .= t('Clubplugin error: you need to enable javascript in your browser to see the Clubplugin competition data.');
	$content .= '</noscript></div>';
	return $content;
}


/**
 * Implements hook_libraries_info().
 *
 * Registers CSS files in libraries/clubplugin for this module.
 */
function clubplugin_libraries_info() {
	$libraries = array();
	$libraries['clubplugin'] = array(
		'name' => 'Onsweb Clubplugin',
		'vendor url' => CLUBPLUGIN_VENDOR_URI,
		'download url' => CLUBPLUGIN_DOWNLOAD_URI,
		'version' => '0.5',
		'files' => array(
			'css' => array(
				'clubplugin-style.css' => array('group' => CSS_DEFAULT),
				'clubplugin-grey.css' => array('group' => CSS_DEFAULT),
			),
		),
	);
	return $libraries;
}


/**
 * Implements hook_menu().
 *
 * Adds a link in the administration menu, making the configuration interface
 * available to site admins.
 */
function clubplugin_menu() {
	$items = array();
	$items['admin/config/content/clubplugin'] = array(
		'title' => 'Clubplugin',
		'description' => 'Change settings for the Clubplugin.',
		'access arguments' => array('administer clubplugin'),
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('clubplugin_form'),
	);

	return $items;
}


/**
 * Implements hook_form().
 *
 * Page callback that defines the administration interface.
 * @see clubplugin_menu()
 */
function clubplugin_form($form, &$form_state) {
	// Add scriptcode entry field
	$form['clubplugin_scriptcode'] = array(
		'#type' => 'textfield',
		'#title' => t('Script code'),
		'#description' => sprintf(t('The script code as received after registration. It contains between 22 and 32 alphanumeric characters. If you don\'t have a script code, contact <a href="%s">Onsweb Support desk</a> for help.'), CLUBPLUGIN_VENDOR_URI),
		'#default_value' => variable_get('clubplugin_scriptcode'),
		'#maxlength' => 32,
	);

	// Find out if library is available
	$library = libraries_detect('clubplugin');
	if(!empty($library['installed'])) {
		// show success
		$library_available = theme_image(array('path' => 'misc/message-16-ok.png', 'attributes' => array()));
		$library_available .= ' '. t('The <em>Onsweb Clubplugin</em> library is installed.');
	} else {
		// show error message from libraries api
		$library_available = theme_image(array('path' => 'misc/message-16-error.png', 'attributes' => array()));
		$library_available .= ' '. $library['error message'];
	}

	$form['clubplugin_library_available'] = array(
		'#type' => 'item',
		'#title' => t('Library available?'),
		'#markup' => $library_available,
		'#description' => sprintf(t('If the library files aren\'t installed, you need to <a href="%s">download them</a> and place the .css files in the sites/all/libraries/clubplugin directory'), CLUBPLUGIN_DOWNLOAD_URI),
	);

	return system_settings_form($form);
}


/**
 * Implements Form API's _validate().
 *
 * Validate that the provided script code matches the format as
 * specified in Onsweb clubplugin documentation.
 */
function clubplugin_form_validate($form, &$form_state) {
	$scriptcode = $form_state['values']['clubplugin_scriptcode'];

	//if (strlen($scriptcode) < 22 || strlen($scriptcode) > 32) {
	if (!ctype_alnum($scriptcode)) {
		form_set_error('clubplugin_scriptcode', t('Your script code can only contain alphanumeric characters: a-z and 0-9.'));
	} elseif (strlen($scriptcode) < 20 || strlen($scriptcode) > 32) {
		form_set_error('clubplugin_scriptcode', t('Your script code must contain between 22 and 32 characters.'));
	}
}


/**
 * Implements hook_permission().
 *
 * Define access control for clubplugin administration interface.
 */
function clubplugin_permission() {
	return array(
		'administer clubplugin' => array(
			'title' => t('Administer Clubplugin settings'),
		)
	);
}
